### ISSUE TITLE
Add an Eclipse project structure

### ISSUE THREAD

**Issue by OstapKryvytskyy** [ITisIT/itisit#7]
(with settings)

**Comment by OlexiiLysenko** [comment]
Hi everyone!
So, **_what_** we gonna do here in this issue?
@OstapKryvytskyy , shall we discuss adding an Eclipse project structure to our **ITisIT** repo?

**Comment by VictorShyshkin** [comment]
I think we have to wait for some guidance from Ostap

**Comment by OstapKryvytskyy** [comment]
Sure. Will do. But let's be in the decision, that it is an open project and not everything is done so quickly. I'll discuss close source possibility later. Now I'll try to add a complex eclipse settings only for your understanding. Thanks, estimate is up to a moment.
